# numpy practice 

In [1]:
# step 1 is to install numpy library 
# step 2 is to import numpy library 

import numpy as np 
food = np.array(["samosa", "pakora", "raita"])
food 

array(['samosa', 'pakora', 'raita'], dtype='<U6')

In [2]:
# checking the length of the array 
len(food)

3

In [3]:
# checking the indexing 
food[0]

'samosa'

In [4]:
food[0:]

array(['samosa', 'pakora', 'raita'], dtype='<U6')

In [5]:
food[1:2]

array(['pakora'], dtype='<U6')

In [ ]:
# now declring an other array called as prices

In [6]:
price =  np.array([5, 5, 6])
price

array([5, 5, 6])

In [7]:
type(price)

numpy.ndarray

In [8]:
price.mean()

5.333333333333333

In [9]:
price.max()

6

# different methods of arrays

In [10]:
# zeros method 
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
# ones method 
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [12]:
# empty method 
np.empty(5)

array([0., 0., 0., 0., 0.])

In [13]:
# arrange method 
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [14]:
# specific range 
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [16]:
# specific range with specific intervl 
np.arange(2, 20, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
# specific line space 
np.linspace(2, 20, num=20)

array([ 2.        ,  2.94736842,  3.89473684,  4.84210526,  5.78947368,
        6.73684211,  7.68421053,  8.63157895,  9.57894737, 10.52631579,
       11.47368421, 12.42105263, 13.36842105, 14.31578947, 15.26315789,
       16.21052632, 17.15789474, 18.10526316, 19.05263158, 20.        ])

In [21]:
# Differnt types of numbers 
np.ones(50, dtype = np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [22]:
# float data 
np.ones(50, dtype = np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Array Function

In [23]:
a = np.array([10, 12, 15, 2, 4, 6, 100, 200, 10.0, 12.4])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 200. ,  10. ,
        12.4])

In [26]:
a.sort()
a

array([  2. ,   4. ,   6. ,  10. ,  10. ,  12. ,  12.4,  15. , 100. ,
       200. ])

In [29]:
import numpy as np
b = np.array([2.5, 4l.2, 56.4, 64, 245, 67, 24, 678])
b

SyntaxError: invalid syntax (Temp/ipykernel_10528/249058242.py, line 2)

In [32]:
b = np.array([10.5,23,345,64.5,753.1,67])
b

array([ 10.5,  23. , 345. ,  64.5, 753.1,  67. ])

In [35]:
c = np.concatenate((a,b))
c

array([  2. ,   4. ,   6. ,  10. ,  10. ,  12. ,  12.4,  15. , 100. ,
       200. ,  10.5,  23. , 345. ,  64.5, 753.1,  67. ])

In [36]:
c.sort()
c

array([  2. ,   4. ,   6. ,  10. ,  10. ,  10.5,  12. ,  12.4,  15. ,
        23. ,  64.5,  67. , 100. , 200. , 345. , 753.1])

# 2-D arrays 

In [40]:
a = np.array([[1,2],[6,7]])
a

array([[1, 2],
       [6, 7]])

In [41]:
b = np.array([[6,7],[8,9]])
b

array([[6, 7],
       [8, 9]])

In [43]:
c = np.concatenate((a,b), axis = 0)
c

array([[1, 2],
       [6, 7],
       [6, 7],
       [8, 9]])

In [44]:
c = np.concatenate((a,b), axis = 1)
c

array([[1, 2, 6, 7],
       [6, 7, 8, 9]])

# 3-D Arrays 

In [45]:
a = np.array([[[1,2,3],[4,5,6]],
              [[3,4,5],[9,8,6]],
              [[3,2,1],[4,6,7]]])
a

array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 4, 5],
        [9, 8, 6]],

       [[3, 2, 1],
        [4, 6, 7]]])

In [46]:
# to find the dimension of an array 
a.ndim

3

In [47]:
# to check the size (number of elements)
a.size

18

In [48]:
# to check the shape of an array ////// 
#in the result 3 = dimensions, 2 = number of rows in every dimensions, last 3 = number of columns
a.shape

(3, 2, 3)

In [50]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [51]:
# reshape the array   /// it converts actually rows to col and col to rows
b = a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [52]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
b = a.reshape(5,2)
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [54]:
b = a.reshape(2,5)
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [56]:
# another comand for reshape the array 
np.reshape(a, newshape=(2,5), order='C')

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [57]:
np.reshape(a, newshape=(5,2), order='C')

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

# row and col conversion 

In [2]:
import numpy as np 
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a.shape

(9,)

In [3]:
b = a[np.newaxis, :] # row wise 2d conversion 
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [4]:
b.shape

(1, 9)

In [6]:
c = a [:, np.newaxis] # this will convert rows into col
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [7]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
a[2:6]

array([3, 4, 5, 6])

In [10]:
a[2:5]

array([3, 4, 5])

In [11]:
a*6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [12]:
a+6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [15]:
a.sum()

45

In [16]:
a.mean()

5.0

# Practice from the manual 

In [18]:
a = np.array([(1,2,3), (4,5,6)])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
a.ndim

2

In [25]:
a = np.array([[(1,2,3)], [(4,5,6)], [(6,7,8)]])
a

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[6, 7, 8]]])

In [26]:
a.ndim

3

## Different types of data in array 

In [27]:
a = np.array([[1,2], [3,4]], dtype = complex) # this is to priduce the complex data 
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [28]:
a = np.zeros([3,4], dtype=complex)
a

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

In [30]:
a = np.zeros([3,4], dtype=np.int64)
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int64)

In [31]:
a.size

12

In [32]:
a.shape

(3, 4)

In [34]:
a = np.ones([2,3,4])
a

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [40]:
from numpy import pi 
x = np.linspace(0, 2*pi, 10)
f = np.tan(x)
f

array([ 0.00000000e+00,  8.39099631e-01,  5.67128182e+00, -1.73205081e+00,
       -3.63970234e-01,  3.63970234e-01,  1.73205081e+00, -5.67128182e+00,
       -8.39099631e-01, -2.44929360e-16])

## 1D, 2D, and 3D Arrays 

In [44]:
# 1D Array 
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [45]:
a.ndim

1

In [46]:
# 2D Array 
a = np.array([1,2,3,4,5,6]).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
a.ndim

2

In [52]:
# 3D Array
b = np.array([1,2,3,4,5,6,7,8,9,10,11,13,12,14,15,16,17,18]).reshape(2,3,3)
b

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 13],
        [12, 14, 15],
        [16, 17, 18]]])

In [53]:
b.ndim

3

In [55]:
b = np.arange(48).reshape(4,3,4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]],

       [[36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

## Basic Operations